[phases.setup]
nixPkgs = ["python312"]

[phases.build]
cmds = ["cd backend && pip install -r requirements.txt"]

[phases.start]
cmd = "cd backend && python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn magasin_app.wsgi:application --bind 0.0.0.0:$PORT"

[static]
# Set the working directory to backend
workingDir = "/app/backend"
