# Generated by Django 5.0.1 on 2026-08-18 14:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketReparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_ticket', models.CharField(editable=False, max_length=20, unique=True)),
                ('nom_client', models.CharField(max_length=100)),
                ('telephone_client', models.CharField(max_length=20)),
                ('marque_appareil', models.CharField(max_length=100)),
                ('modele_appareil', models.CharField(max_length=100)),
                ('imei_ou_serie', models.CharField(blank=True, max_length=50)),
                ('code_deverrouillage', models.CharField(blank=True, help_text='Code PIN ou schéma de déverrouillage', max_length=200)),
                ('panne_declaree', models.TextField()),
                ('constat_entree', models.TextField(help_text="État général de l'appareil à la réception")),
                ('etat_esthetique', models.TextField(blank=True)),
                ('estimation_prix', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('acompte', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('statut', models.CharField(choices=[('RECU', 'Reçu'), ('DIAGNOSTIC', 'En cours de diagnostic'), ('ATTENTE_PIECE', 'En attente de pièce'), ('EN_REPARATION', 'En réparation'), ('PRET', 'Réparé / Prêt'), ('LIVRE', 'Livré & Réglé'), ('NON_REPARABLE', 'Non réparable')], default='RECU', max_length=20)),
                ('date_reception', models.DateTimeField(auto_now_add=True)),
                ('date_estimation', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('notification_envoyee', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reparations', to='clients.client')),
            ],
            options={
                'verbose_name': 'Ticket de réparation',
                'verbose_name_plural': 'Tickets de réparation',
                'ordering': ['-date_reception'],
            },
        ),
        migrations.CreateModel(
            name='PieceUtilisee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('cout_unitaire', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisations', to='produits.produit')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_utilisees', to='reparations.ticketreparation')),
            ],
            options={
                'verbose_name': 'Pièce utilisée',
                'verbose_name_plural': 'Pièces utilisées',
            },
        ),
    ]
