# Generated by Django 5.0.1 on 2026-08-18 14:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('type_piece', models.CharField(choices=[('CIN', "Carte d'Identité Nationale"), ('PASSEPORT', 'Passeport'), ('CARTE_SEJOUR', 'Carte de séjour')], max_length=20)),
                ('numero_piece', models.CharField(max_length=50)),
                ('photo_piece', models.ImageField(blank=True, null=True, upload_to='pieces_identite/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('VENTE', 'Vente client'), ('ACHAT', 'Achat occasion')], max_length=10)),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('CARTE', 'Carte bancaire'), ('VIREMENT', 'Virement'), ('AVOIR', 'Avoir en magasin'), ('FRACTIONNE', 'Paiement fractionné')], max_length=20)),
                ('contrat_pdf', models.FileField(blank=True, null=True, upload_to='contrats/')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('COMPLETE', 'Complétée'), ('ANNULEE', 'Annulée')], default='EN_COURS', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='clients.client')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date_transaction'],
            },
        ),
        migrations.CreateModel(
            name='LigneTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('garantie_mois', models.IntegerField(default=12)),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_transaction', to='produits.produit')),
                ('telephone_occasion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_transaction', to='produits.telephoneoccasion')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='clients.transaction')),
            ],
            options={
                'verbose_name': 'Ligne de transaction',
                'verbose_name_plural': 'Lignes de transaction',
            },
        ),
    ]
