# Generated by Django 5.0.1 on 2026-08-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='facture_pdf',
            field=models.FileField(blank=True, null=True, upload_to='factures/'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='numero_facture',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
