# Generated by Django 5.0.1 on 2026-08-18 14:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Catégorie de produit',
                'verbose_name_plural': 'Catégories de produits',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_barres', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('type_stock', models.CharField(choices=[('UNIQUE_IMEI', 'Unité unique (avec IMEI)'), ('QUANTITE', 'Quantité en vrac')], default='QUANTITE', max_length=20)),
                ('marque', models.CharField(blank=True, max_length=100)),
                ('modele', models.CharField(blank=True, max_length=100)),
                ('capacite', models.CharField(blank=True, max_length=50)),
                ('couleur', models.CharField(blank=True, max_length=50)),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_min', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True)),
                ('garantie_mois', models.IntegerField(default=12, help_text='Garantie en mois')),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='produits.categorieproduit')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='TelephoneOccasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei1', models.CharField(max_length=15, unique=True)),
                ('imei2', models.CharField(blank=True, max_length=15, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=50)),
                ('grade', models.CharField(choices=[('A', 'Grade A'), ('B', 'Grade B'), ('C', 'Grade C')], default='B', max_length=1)),
                ('etat_cosmetique', models.TextField(help_text="Description de l'état (rayures, fissures, etc.)")),
                ('etat_batterie', models.IntegerField(help_text='État de la batterie en %', validators=[django.core.validators.MinValueValidator(0)])),
                ('statut', models.CharField(choices=[('EN_TEST', 'En test'), ('EN_RECONDITIONNEMENT', 'En reconditionnement'), ('EN_STOCK', 'En stock prêt pour la vente'), ('VENDU', 'Vendu'), ('RESTITUE', 'Restitué')], default='EN_TEST', max_length=20)),
                ('date_achat', models.DateTimeField(auto_now_add=True)),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telephones_occasion', to='produits.produit')),
            ],
            options={
                'verbose_name': "Téléphone d'occasion",
                'verbose_name_plural': "Téléphones d'occasion",
            },
        ),
    ]
