# Generated by Django 5.0.1 on 2026-08-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image_url',
            field=models.URLField(blank=True, help_text="URL de l'image du produit"),
        ),
    ]
